### ISSUE TITLE
Flask host and port are static in exporter conf

### ISSUE THREAD

**Issue by elfosardo** [metal3-io/ironic-image#102]
The change #101 re-introduced the prometheus-exporter app in the ironic image.
This app is based on Flask and in the original configuration its host and running port are statically defined in the startup script runexporterapp.sh
These two parameters should be made customizable and controllable from outside the container.

**Comment by iurygregory** [comment]
The port comes from https://github.com/prometheus/prometheus/wiki/Default-port-allocations 
more details why they do this can be found in https://prometheus.io/docs/instrumenting/writing_exporters/#port-numbers
