### ISSUE TITLE
Mariadb fails to start on Minikube

### ISSUE THREAD

**Issue by maelk** [metal3-io/ironic-image#112]
Mariadb fails to start on the latest Minikube : 
```
Installing MariaDB/MySQL system tables in '/var/lib/mysql' ...
/usr/bin/mysql_install_db: line 469:    35 Killed                  "$mysqld_bootstrap" $defaults $defaults_group_suffix "$mysqld_opt" --bootstrap $silent_startup "--basedir=$basedir" "--datadir=$ldata" --log-warnings=0 --enforce-storage-engine="" "--plugin-dir=${plugindir}" $args --max_allowed_packet=8M --net_buffer_length=16K

Installation of system tables failed!  Examine the logs in
/var/log/mariadb/mariadb.log or /var/lib/mysql for more information.
```

The log files / folders in /shared, /var/log and /var/lib/mysql are empty. 
The container starts properly when not in Minikube (tested on Centos and Ubuntu).

**Comment by maelk** [comment]
When starting the container, the nginx-ingress-controller and storage-provisioner of Minikube crash too

**Comment by maelk** [comment]
We could trace the failure to a suspicious mmap call :
```
[pid    89] mmap(NULL, 17179869184, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f53e5f99000
[pid    89] +++ killed by SIGKILL +++
```
that causes OOM killer to come in action.

**Comment by hardys** [comment]
> We could trace the failure to a suspicious mmap call :

Did you find a related upstream bug that suggested an upgrade would fix this?

cc @elfosardo have you seen this while testing with downstream images?

**Comment by maelk** [comment]
Here is the upstream bug : https://github.com/kubernetes/minikube/issues/5751

**Comment by russellb** [comment]
I think we only give minikube 2 GB RAM. It could be that we need to increase after moving ironic and supporting services into the cluster.

**Comment by maelk** [comment]
the amount of RAM is ok for now. Mariadb was requesting 17GB ! :laughing:
