### ISSUE TITLE
isolinux.bin file not found in image

### ISSUE THREAD

**Issue by yrobla** [metal3-io/ironic-image#137]
When enrolling nodes with virtualmedia, they get the error about couldn't create ISO because isolinux.bin file does not exist.
I actually logged into ironic-conductor pod and the /usr/lib/syslinux/isolinux.bin is not there. Even more, i installed syslinux package on ironic-conductor and i see the file goes to /usr/share/syslinux/isolinux.bin . Something may have changed in the base image.
A possible solution is install syslinux package on the ironic-image + creating a soft link to point to /usr/lib/syslinux/isolinux.bin

**Comment by etingof** [comment]
This might only happen if you do BIOS boot as opposed to UEFI.

Perhaps [default/isolinux_bin](https://github.com/openstack/ironic/blob/master/ironic/conf/default.py#L196) ironic option can  be used to point ironic to proper `isolinux.bin` location.

**Comment by yrobla** [comment]
In my case, the installer host is UEFI and also the target node has boot mode as UEFI.

**Comment by elfosardo** [comment]
As far as I can tell we never installed the syslinux package explicitly.
I also don't see it being installed as dependency from other packages, at least looking at some of the history of the builds.
If this is a new requirement for vmedia boot we definitely need to install it.
Either softlink or change of ironic option should work fine afterwards.

**Comment by etingof** [comment]
> This might only happen if you do BIOS boot as opposed to UEFI.
> 
> Perhaps [default/isolinux_bin](https://github.com/openstack/ironic/blob/master/ironic/conf/default.py#L196) ironic option can be used to point ironic to proper `isolinux.bin` location.

This seems surprising to me because [of this condition](https://github.com/openstack/ironic/blob/master/ironic/common/images.py#L498). I can't find any other path leading to `isolinux.bin` use.

Could you share some logs to see where it ultimately went?

**Comment by etingof** [comment]
> As far as I can tell we never installed the syslinux package explicitly.
> I also don't see it being installed as dependency from other packages, at least looking at some of the history of the builds.

May be this is up to the package (e.g. rpm) to take care of a non-Pythonic dependency? We do install it in devstack. though.

> If this is a new requirement for vmedia boot we definitely need to install it.
> Either softlink or change of ironic option should work fine afterwards.

Prior to redfish virtual media, I think `ilo` driver might have used `isolinux` similarly.

Also, it should be a kind of conditional dependency - UEFI boot should work just fine without isolinux.

**Comment by yrobla** [comment]
This is happening just with virtualmedia i'd say, because it needs to compose the iso for the system to use it. So this fails on the process of iso creation

**Comment by stbenjam** [comment]
@elfosardo Could you take a look at this? Do we need to add this package to ironic-image for virtual media?

**Comment by yrobla** [comment]
I got rid of this failure on master nodes , using latest code. If the box is uefi, that file should not be used. However i am starting to see the same failures on worker nodes now, with a box booting from uefi.

**Comment by juliakreger** [comment]
using latest code from where? metal3-io/ironic-image, openshift/ironic-image, ironic itself?

**Comment by yrobla** [comment]
Latest code from openshift/installer... it sets capabilities/boot_mode to uefi by default . With that flag, the isolinux.bin codepath is not reached, and i do not get the missing file problem.

**Comment by juliakreger** [comment]
@yrobla In that case, it seems like we could close this item?

**Comment by yrobla** [comment]
Closing that, as boot_mode:uefi capability fixes the issue
