### ISSUE TITLE
IP conflicts on dnsmasq crash PXE firmware

### ISSUE THREAD

**Issue by ismacasti** [metal3-io/ironic-image#195]
Hi!

We have encountered a problem with conflicting IPs on dnsmasq on Dell hardware. It is well explained on a bug in Ironic's bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1301659
```
$> kubectl logs metal3-ironic-57bc4b8958-qqtp8 -n dc254-cluster-capi -c ironic-dnsmasq | grep 172.18.0.43  
dnsmasq-dhcp: 1453030933 DHCPOFFER(provisionnet) 172.18.0.43 98:a4:04:22:2e:a0 
dnsmasq-dhcp: 1375794672 DHCPOFFER(provisionnet) 172.18.0.43 e4:43:4b:c1:4a:78 
dnsmasq-dhcp: 1453030933 DHCPOFFER(provisionnet) 172.18.0.43 98:a4:04:22:2e:a0 
dnsmasq-dhcp: 1453030933 DHCPREQUEST(provisionnet) 172.18.0.43 98:a4:04:22:2e:a0 
dnsmasq-dhcp: 1453030933 DHCPACK(provisionnet) 172.18.0.43 98:a4:04:22:2e:a0 
dnsmasq-dhcp: 1375794672 DHCPREQUEST(provisionnet) 172.18.0.43 e4:43:4b:c1:4a:78 
dnsmasq-dhcp: 1375794672 DHCPNAK(provisionnet) 172.18.0.43 e4:43:4b:c1:4a:78 address in use
```
The moment that NAK gets to the machine, PXE stops and the machine moves to boot from HDD. (Thanks Dell for your good DHCP implementation)

The workaround described there is to have Ironic serve sequential IP.
Could you add this workaround to the metal³ ironic?

Thanks a lot!

**Comment by maelk** [comment]
/kind bug
@dtantsur @derekhiggins @elfosardo any idea whether doing this kind of changes in the dnsmasq configuration would impact Metal3 negatively ?

**Comment by dtantsur** [comment]
It's a good idea, I'm all for it. I don't expect any particular downsides.

**Comment by derekhiggins** [comment]
Sounds ok to me, apparently this increases the chances that the IP for a host might change if the client allows the lease to expire which I guess could happen if a node powered down, @celebdor do you know if this would be handled ok in openshift?
```
       --dhcp-sequential-ip
              <snip/> Note that in the sequential mode, clients which allow a lease to expire are much more likely to move IP address; for this reason it should not be generally used.
```
