### ISSUE TITLE
Basic auth on json-rpc broken with IPv6

### ISSUE THREAD

**Issue by zaneb** [metal3-io/ironic-image#210]
There is a [bug in Ironic](https://storyboard.openstack.org/#!/story/2008288) with json-rpc when specifying an IPv6 address for the `[DEFAULT].host` config option for ironic-conductor.

Since #201 we explicitly set this option to `$IRONIC_IP` except when the json-rpc auth type is `noauth` (in which case it's forced to be `localhost`).

Until the bug is fixed, basic auth on json-rpc is unusable with IPv6.

**Comment by maelk** [comment]
Hum, we could remove the line that explicitly sets it to $IRONIC_IP. That's how it worked until this PR, so I don't see a problem reverting to this behaviour
