### ISSUE TITLE
missing consol logging makes bmh provisioning fail

### ISSUE THREAD

**Issue by knfoo** [metal3-io/ironic-image#228]
After upgrade to v0.4.1 the bmh no longer logs syslog to the console during the different phases.
It seems to do with this: https://github.com/metal3-io/ironic-image/pull/160
This for some odd reason has the effect on my baremetal nodes (Hauwei ibmc managed, UEFI and Legacy bootmode) that it fails in random phases like clean wait, inspection wait. 
I am not able to get anything to provision the servers as they all get stuck in clean wait.
After help from the community slack https://kubernetes.slack.com/archives/CHD49TLE7/p1606294233210600
I was able to get syslog to consol re-enabled in the ironic-image.

What did to get it back in working state:
I added ssh-debugging in order to get in the the image and try to run some debugging steps to figure out what was wrong
https://github.com/metal3-io/ironic-image/pull/226

Then I rebuild the ironic-image to get the required parameters included in the `inspector.ipxe.j2`- I have this file do to the work in the https://github.com/metal3-io/ironic-image/pull/226 - and the `ironic.conf.j2` and enabled the `systemd.journald.forward_to_console=yes`

This getting the console logging back I am now able to get the bmh to behave as expected, from inspection to full deployment.

At least for me having the possibility to switch on console logging via a env variable would work better than having to hack the image on every new release.

**Comment by knfoo** [comment]
The changes I did is available in this fork
 https://github.com/knfoo/ironic-image

**Comment by derekhiggins** [comment]
I've updated https://github.com/metal3-io/ironic-image/pull/226 to remove console=ttyS0 form the kernel, it can now instead be configured.

**Comment by knfoo** [comment]
That sounds great
