### ISSUE TITLE
Ironic does not support ilo5

### ISSUE THREAD

**Issue by mel1nn** [metal3-io/ironic-image#243]
I want to provision a baremetal server (HPE) using its ilo5 bmc.
When I apply the related baremetalhost on my cluster, an error occurs in the Ironic pod:
` No valid host was found. Reason: No conductor service registered which supports driver ilo5 for conductor group`.

Thanks for your help.

**Comment by hardys** [comment]
This will be closed via https://github.com/metal3-io/ironic-image/pull/244
