### ISSUE TITLE
runmariadb seems to fail with MariaDB 10.3.28

### ISSUE THREAD

**Issue by kunyi731** [metal3-io/ironic-image#254]
The latest centos8 build would update MariaDB to 10.3.28 and it seems the current runmariadb script doesn't work well with it.
I'm seeing the mariadb pod crash after the update. After pinning the mariadb-server version to 10.3.27 the issue is resolved.

This is the log of failing mariadb pod: https://pastebin.com/EAUpevfx

**Comment by namnx228** [comment]
Temporary fix: https://github.com/metal3-io/ironic-image/pull/259
Proper fix: https://github.com/metal3-io/ironic-image/pull/260
