### ISSUE TITLE
Image metal3-io/ironic:capm3-v0.5.4 unavailable

### ISSUE THREAD

**Issue by tpaimparay** [metal3-io/ironic-image#341]
Hello,
Image metal3-io/ironic:capm3-v0.5.4 is not available in quay.io.

Could you have a look ?

BR

**Comment by furkatgofurov7** [comment]
Hey @tpaimparay !
Thanks for reaching out. We are facing some issues with our image builds in quay recently and a support ticket towards quay has been opened to resolve this. Sorry for the inconvenience and I will make sure to give an update here once we sort out the issue. The same notification has been sent out in [bare metal slack channel ](https://kubernetes.slack.com/archives/CHD49TLE7/p1641289164319100)

**Comment by tpaimparay** [comment]
Thanks for your quick answer and actions.

BR

**Comment by furkatgofurov7** [comment]
Hi!

Quay issue has been resolved and the image is available now: [quay.io/metal3-io/ironic:capm3-v0.5.4](https://quay.io/repository/metal3-io/ironic?tag=capm3-v0.5.4&tab=tags)

Thanks for your patience!
