### ISSUE TITLE
It would be great to have health checks compatible with kubernetes.

### ISSUE THREAD

**Issue by imain** [metal3-io/ironic-image#41]
The current arrangement of having the container exit on failure is not a standard method of performing health checks in kubernetes (or other container systems). 

In kubernetes you would usually use a livenessProbe which can specify a command.  This is essentially exec'd every n seconds and the result is checked.  Multiple failures can result in the container being restarted.  This is especially nice because the failures are logged and you can still get logs of a failing container.  Also for debug purposes you can disable the healthcheck and still exec into the container.

see eg:  https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

I thought podman does not natively support these, but it seems I was wrong.  There is some information on how to do this here:

https://developers.redhat.com/blog/2019/04/18/monitoring-container-vitality-and-availability-with-podman/

Thanks everyone!   These containers are getting better all the time!

**Comment by bfournie** [comment]
Based on the experience that OSP is having using 'podman exec' for healthchecks and the resulting memory leaks [0] we should hold off on switching to this method until the podman issue is resolved.

[0] https://bugzilla.redhat.com/show_bug.cgi?id=1699202
