### ISSUE TITLE
Nova power notification warning in log

### ISSUE THREAD

**Issue by hjensas** [metal3-io/ironic-image#444]
This is cosmetic, but I see this in logs:

> `2023-11-14T16:22:22.129348983+00:00 stderr F 2023-11-14 16:22:22.126 1 WARNING ironic.common.nova [None req-1393f16f-2b67-47ff-9173-2592fe139b74 - - - - - -] Could not connect to Nova to send a power notification, please check configuration. An auth plugin is required to determine endpoint URL: keystoneauth1.exceptions.auth_plugins.MissingAuthPlugin: An auth plugin is required to determine endpoint URL[00m

I think we can save some CPU cycles and disable that by adding?
```
[nova]
send_power_notifications = false
```

**Comment by elfosardo** [comment]
@hjensas thanks!
feel free to propose a patch
