### ISSUE TITLE
We still have logs in the filesystem.

### ISSUE THREAD

**Issue by imain** [metal3-io/ironic-image#46]
We shouldn't be logging to the filesystem.  We still have logs going into the shared volume.  Eventually this will just balloon and cause problems.  All logs should go to stdout, or else we need to implement a log rotation scheme.

**Comment by dtantsur** [comment]
This is correct, and we're close to fixing it. However, the ramdisk logs are just tarballs, we cannot put them to stdout.

**Comment by imain** [comment]
OK that's fine.  It is part of the interface in kubernetes that the containers log to stdout.  That way you can get logs via the command line.

**Comment by dtantsur** [comment]
We still have log files because of https://github.com/rdo-packages/ironic-distgit/commit/64c9b5062638ff07d757afab8b9ca9e92a449051, will fix.
