### ISSUE TITLE
metal3-static-ip-set init container fails when there are two interfaces with same MAC and provisioningInterface is not set

### ISSUE THREAD

**Issue by machacekondra** [metal3-io/ironic-image#530]
When `metal3-static-ip-set` init container is executed on env where there two interface with same MAC address following script:
[metal3-static-ip-set init container](https://github.com/metal3-io/ironic-image/blob/main/scripts/ironic-common.sh#L29)
```bash
interface="$(ip -br link show up | grep -i "$mac" | cut -f 1 -d ' ' | cut -f 1 -d '@')"
```

fails, as it returns both interfaces delimited by new line and so the init container fails, because later such interface name don't exist. Here is example of failed script execution:

```bash
+ '[' -z '' ']'
+ '[' -n 78:ac:44:05:35:fc,78:ac:44:06:61:96,78:ac:44:06:62:62 ']'
+ for mac in ${PROVISIONING_MACS//,/ }
+ ip -br link show up
+ grep -qi 78:ac:44:05:35:fc
++ ip -br link show up
++ grep -i 78:ac:44:05:35:fc
++ cut -f 1 -d ' '
+ PROVISIONING_INTERFACE='eno3
br-ex'
+ break
+ '[' -n 'eno3
br-ex' ']'
++ ip -o addr show dev 'eno3
br-ex' scope global
Device "eno3
br-ex" does not exist.
+ [[ -n '' ]]
+ /usr/sbin/ip address flush dev 'eno3
br-ex' scope global
Device "eno3
br-ex" does not exist.
```

As you can see it tries to find interface:
```
eno3
br-ex
```

Workaround is edit `provisioning` resource `provisioning-configuration` with following configuration:
```
spec:
    ...
    provisioningInterface: eno3
    ...
```

Is there a way to specify such configuration in openshift install config?

**Comment by dtantsur** [comment]
Note: `metal3-static-ip-set` is specific to OpenShift, but I suspect the bug equally applies to upstream containers.
