### ISSUE TITLE
ipa-inspection-callback-url=mdns breaks inspection in BMO pod.

### ISSUE THREAD

**Issue by imain** [metal3-io/ironic-image#54]

**Comment by imain** [comment]
I'm getting an error from inspection as per the screenshot provided.  I'm guessing we need to revert that change.  There's no DNS supplying information for the ironic pod as to where the inspection endpoint would be.
![Screenshot from 2019-06-11 14-36-12](https://user-images.githubusercontent.com/169081/59308814-d29b9b00-8c56-11e9-9a2f-a9f2686c9b41.png)

**Comment by elfosardo** [comment]
this feature is quite new, do you have the latest IPA ?

**Comment by dtantsur** [comment]
This is old IPA, please update it. The mDNS record is served by the ironic-inspector container, but your IPA image does not understand it.

**Comment by imain** [comment]
Thanks that fixed it.
