### ISSUE TITLE
ironic-log-watch: CPU at full capacity in case of no ramdisk file present 

### ISSUE THREAD

**Issue by blallau** [metal3-io/ironic-image#547]
In the ironic-log-watch container when no ramdisk file is present in /shared/log/ironic/deploy directory an infinite loop lead cpu to be at full capacity all the time.

**Comment by tuminoid** [comment]
We have https://github.com/metal3-io/ironic-image/pull/540 already addressing the same, can you please collaborate on that PR?

**Comment by Rozzii** [comment]
After some discussion in the coumminty @blallau 's PR https://github.com/metal3-io/ironic-image/pull/548 was chosen as the better solution and https://github.com/metal3-io/ironic-image/pull/540 was closed
So I will accept this Issue as it is related to the fix PR.
/triage accepted
/kind bug
