### ISSUE TITLE
Ironic listening on all interfaces, not only my_ip

### ISSUE THREAD

**Issue by hardys** [metal3-io/ironic-image#55]
We pass a PROVISIONING_INTERFACE so that we can bind the ironic services only to a specific internal network, but it seems like the my_ip configuration isn't enough, netstat shows the service (and inspector) listening on all all interfaces?

```
$ sudo netstat -taupen | grep 6385
tcp        0      0 0.0.0.0:6385            0.0.0.0:*               LISTEN      0          1822447    12064/python2       
tcp        0      0 127.0.0.1:55478         127.0.0.1:6385          TIME_WAIT   0          0          -                   
$ sudo podman exec -it ironic cat /etc/ironic/ironic.conf | grep my_ip
my_ip = 172.22.0.2
```

Am I missing something, or do we need some additional configuration to ensure binding to the expected interface?

**Comment by stbenjam** [comment]
@hardys mentioned that locking down Ironic to only listen on the provisioning interface broke some communication, as something was trying to talk to it on a different IP. This needs more investigation

**Comment by hardys** [comment]
> @hardys mentioned that locking down Ironic to only listen on the provisioning interface broke some communication, as something was trying to talk to it on a different IP. This needs more investigation

https://github.com/metal3-io/ironic-image/pull/56 has some more details on this, I think the main issue is some things expect to use localhost, not only the provisioning IP so we'll need to address that before fixing this.

**Comment by dtantsur** [comment]
The option is `[api]host_ip`, `my_ip` is used by conductor for different purpose.

**Comment by fmuyassarov** [comment]
Hi @hardys . Do you have any updates on this issue? We were not sure if there was a progress on this issue while triaging today. But perhaps you can share the status?

**Comment by mboukhalfa** [comment]
Previous PR has been merged not sure why are not mentioned here probably once the PR #372  we can close the issue

**Comment by Rozzii** [comment]
I think this has been fixed , can you please close it @hardys ?
