### ISSUE TITLE
Every container runs 'configure-ironic.sh': Required inputs unclear

### ISSUE THREAD

**Issue by imain** [metal3-io/ironic-image#68]
The container are split up now but I'm not sure which configuration options are important to which containers.  I'm configuring them all for now but things like the http port etc may not be required by all containers?

I guess this is really just a docs request, we should update the README.

**Comment by dtantsur** [comment]
With https://github.com/metal3-io/ironic-image/pull/64 we'll have much fewer options that are configured in runtime, will it solve your issue?

**Comment by stbenjam** [comment]
It looks like README.md has some documentation now, but it may be out of date after the changes for IPv6.
