### ISSUE TITLE
cp: cannot stat '/usr/share/ipxe/ipxe.efi': No such file or directory

### ISSUE THREAD

**Issue by e-minguez** [metal3-io/ironic-image#95]
https://github.com/metal3-io/ironic-image/blob/2bca55e0f4198cb0d8500f551bcb26c573a9bf3a/rundnsmasq.sh#L22

`podman logs dnsmasq` complains about `cp: cannot stat '/usr/share/ipxe/ipxe.efi': No such file or directory`

according to `rpm -ql ipxe-bootimgs-20181214-1.git133f4c47.el8.noarch | grep ipxe` there are two efi files:
```
/usr/share/ipxe/ipxe-i386.efi
/usr/share/ipxe/ipxe-x86_64.efi
```

**Comment by dtantsur** [comment]
Note that we need to keep compatibility with CentOS 7.
